- name: configure the backend server
  hosts: backend
  become: yes
  vars_files:
    credentials.yaml
  vars_prompt:
    - name: password
      prompt: enter the passowrd?
      private: false
  roles:
  - backend